export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: "Gul naqshli ko'ylak",
    price: 189000,
    discount_price: 149000,
    images: ['https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg'],
    sizes: ['S', 'M', 'L'],
    colors: ['Pushti', 'Oq'],
    is_featured: true,
    category_id: null,
  },
  {
    id: '2',
    name: "Yozgi sitsa ko'ylak",
    price: 215000,
    discount_price: null,
    images: ['https://images.pexels.com/photos/7691168/pexels-photo-7691168.jpeg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Ko\'k'],
    is_featured: false,
    category_id: null,
  },
  {
    id: '3',
    name: 'Zamonaviy kofta',
    price: 245000,
    discount_price: 199000,
    images: ['https://images.pexels.com/photos/6069552/pexels-photo-6069552.jpeg'],
    sizes: ['S', 'M'],
    colors: ['Qora', 'Kulrang'],
    is_featured: true,
    category_id: null,
  },
  {
    id: '4',
    name: 'Elegantli yubka',
    price: 175000,
    discount_price: null,
    images: ['https://images.pexels.com/photos/6311600/pexels-photo-6311600.jpeg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Qora'],
    is_featured: false,
    category_id: null,
  },
  {
    id: '5',
    name: 'Yozgi palto',
    price: 420000,
    discount_price: 369000,
    images: ['https://images.pexels.com/photos/6311387/pexels-photo-6311387.jpeg'],
    sizes: ['M', 'L'],
    colors: ['Bej', 'Oq'],
    is_featured: true,
    category_id: null,
  },
  {
    id: '6',
    name: "Libos to'plami",
    price: 299000,
    discount_price: null,
    images: ['https://images.pexels.com/photos/7691159/pexels-photo-7691159.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Pushti', 'Lila'],
    is_featured: false,
    category_id: null,
  },
  {
    id: '7',
    name: "Chiroyli ko'ylak",
    price: 165000,
    discount_price: 139000,
    images: ['https://images.pexels.com/photos/6069559/pexels-photo-6069559.jpeg'],
    sizes: ['S', 'M'],
    colors: ['Sariq'],
    is_featured: false,
    category_id: null,
  },
  {
    id: '8',
    name: 'Zamonaviy libos',
    price: 310000,
    discount_price: null,
    images: ['https://images.pexels.com/photos/6311582/pexels-photo-6311582.jpeg'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Qizil', 'Qora'],
    is_featured: true,
    category_id: null,
  },
]
